# The electron-builder config for the production site (https://shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client
extraResources:
  - game/dist/**
files:
  - '!**/*.map'
  - '!build/**/*'
  - '!node_modules/**/*'
  - 'index.html'
  - 'assets/**/*'
  - '!dist/index.js'
  - '!dist/preload.js'
  - '!dist/**/*.appchunk.js'
  - 'dist/**/*.js'
  - from: 'dist/'
    to: './'
    filter:
      - 'index.js'
      - 'preload.js'
      - '**/*.appchunk.js'
      - 'native/**/*.node'
nsis:
  artifactName: '${productName}-setup-${version}.${ext}'
win:
  certificateSubjectName: Fast Expo Collective LLC
  signingHashAlgorithms:
    - sha256
  signDlls: true
  rfc3161TimeStampServer: http://ts.ssl.com
  icon: icon.ico
  target: nsis

# These properties differ between configs
productName: ShieldBattery
publish:
  provider: spaces
  name: shieldbattery-cdn
  region: nyc3
  path: /app/
