name: server-rs CI

on:
  push:
    paths:
      - '.github/workflows/server-rs-ci.yml'
      - 'schema.graphql'
      - 'server-rs/**'
  pull_request:
    paths:
      - '.github/workflows/server-rs-ci.yml'
      - 'schema.graphql'
      - 'server-rs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-rs
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./server-rs

      - name: clippy
        run: cargo clippy --all-targets --workspace -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-rs
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: rustfmt
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-rs
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./server-rs

      - name: cargo install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: cargo sqlx prepare --check
        id: sqlx-prepare
        run: cargo sqlx prepare --check --workspace -- --all-targets --all-features

      - name: Display sqlx prepare error
        if: ${{ failure() && steps.sqlx-prepare.conclusion == 'failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('sqlx prepare check failed, please run `cargo sqlx prepare --workspace -- --all-targets --all-features` and check in the changes')

      - name: cargo test
        run: cargo test --all-targets --no-fail-fast
